# https://dart-lang.github.io/linter/lints/
analyzer:
  exclude:
    - lib/**/*.g.dart
linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - file_names
    - prefer_single_quotes
    - unnecessary_this
