name: flutter_starter_pack
description: Base architecture for a Flutter app to get started quickly.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  json_annotation: ^3.1.0
  logger: ^0.9.4
  meta: ^1.2.3
  path: ^1.7.0
  path_provider: ^1.6.22
  provider: ^4.3.2+2
  sembast: ^2.4.7+7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
   - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
